# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='student_profiles',
            field=models.ManyToManyField(blank=True, related_name='instructor_profiles', to='accounts.LearnerProfile'),
        ),
    ]
