# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='accounts.InstructorProfile'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='accounts.LearnerProfile'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='target_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='environments.Language'),
        ),
    ]
